name: qr_image_generator
description: Generate and save QR Code Image.
version: 0.1.0
homepage: https://github.com/Manty-K/QR-Image-Generator

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  qr: ^3.0.1
  image: ^4.0.8

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
