name: qr_image_generator
description: Generate and save QR Code Image. Just provide path and file name.
version: 0.2.5

homepage: https://github.com/Manty-K/QR-Image-Generator

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  qr: ^3.0.1
  image: ^4.0.10
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
